extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:vue/vue3-recommended
  - prettier
parser: vue-eslint-parser
parserOptions:
  parser: "@typescript-eslint/parser"
  project: ./tsconfig.json
  extraFileExtensions:
    - .vue
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-non-null-assertion": off
